suppressPackageStartupMessages({library(readr); library(dplyr); library(purrr); library(fixest)})
base_dir <- "outputs/stage3g_final_inference"
out_dir <- "outputs/stage3j_influence_robustness"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
country_var <- "borrower_country_final"; year_var <- "year"
focus_countries <- c("Sri Lanka", "Philippines")
req <- file.path(base_dir, c("01_financial_final_data.csv", "02_legal_final_data.csv", "03_final_hypotheses.csv"))
if (any(!file.exists(req))) stop("Missing Stage 3G input(s): ", paste(req[!file.exists(req)], collapse = ", "), call. = FALSE)
fin <- read_csv(req[1], show_col_types = FALSE); legal <- read_csv(req[2], show_col_types = FALSE)
targets <- read_csv(req[3], show_col_types = FALSE) %>% filter(hypothesis_id %in% c("F1", "F2", "L2", "L3", "L4"))
drop_singletons <- function(x) { repeat { n0 <- nrow(x); bc <- x %>% count(.data[[country_var]]) %>% filter(n <= 1) %>% pull(1); if(length(bc)) x <- x %>% filter(!(.data[[country_var]] %in% bc)); by <- x %>% count(.data[[year_var]]) %>% filter(n <= 1) %>% pull(1); if(length(by)) x <- x %>% filter(!(.data[[year_var]] %in% by)); if(nrow(x) == n0) return(x) } }
controls_for <- function(d, block, y) { z <- intersect(c("log_loan_amount", "creditor_type"), names(d)); if(block == "financial" && y == "pricing_rate_t0") z <- c(z, intersect(c("maturity_years", "grace_period_years"), names(d))); if(block == "financial" && y == "maturity_years") z <- c(z, intersect("grace_period_years", names(d))); if(block == "legal") z <- c(z, intersect(c("maturity_years", "grace_period_years"), names(d))); unique(z) }
make_sample <- function(d, block, y, g) { z <- controls_for(d, block, y); v <- unique(c("main_sample", country_var, year_var, y, g, z)); list(data = d %>% filter(main_sample == 1) %>% filter(if_all(all_of(v), ~ !is.na(.x))) %>% drop_singletons(), controls = z) }
stats <- function(m, term) { ct <- coeftable(m); if(!(term %in% rownames(ct))) return(c(beta=NA_real_, se=NA_real_, p=NA_real_)); c(beta=unname(ct[term,1]), se=unname(ct[term,grep("Std",colnames(ct),value=TRUE)[1]]), p=unname(ct[term,grep("Pr",colnames(ct),value=TRUE)[1]])) }
fit_main <- function(d, y, g, z, omit=character(), winsor=NULL) { d <- d %>% filter(!(.data[[country_var]] %in% omit)) %>% drop_singletons(); if(!is.null(winsor)) {q <- quantile(d[[y]], winsor, na.rm=TRUE, names=FALSE); d[[y]] <- pmin(pmax(d[[y]],q[1]),q[2])}; f <- as.formula(paste0(y," ~ ",paste(c(g,z),collapse=" + ")," | ",country_var," + ",year_var)); m <- tryCatch(feols(f,data=d,cluster=country_var,fixef.rm="none"),error=function(e)NULL); s <- if(is.null(m)) c(beta=NA_real_,se=NA_real_,p=NA_real_) else stats(m,g); tibble(nobs=if(is.null(m))nrow(d) else nobs(m),clusters=n_distinct(d[[country_var]]),beta=s["beta"],se=s["se"],p=s["p"]) }
fit_slope <- function(d, y, g, z, cc) { d <- d %>% mutate(.focus=as.integer(.data[[country_var]]==cc)); f <- as.formula(paste0(y," ~ ",paste(c(g,paste0(g,":.focus"),z),collapse=" + ")," | ",country_var," + ",year_var)); m <- tryCatch(feols(f,data=d,cluster=country_var,fixef.rm="none"),error=function(e)NULL); if(is.null(m)) return(tibble(focus_country=cc,beta_other=NA_real_,delta_focus=NA_real_,beta_focus=NA_real_,p_delta=NA_real_)); ct <- coeftable(m); it <- paste0(g,":.focus"); b <- stats(m,g)["beta"]; delta <- if(it %in% rownames(ct))unname(ct[it,1]) else NA_real_; pd <- if(it %in% rownames(ct))unname(ct[it,grep("Pr",colnames(ct),value=TRUE)[1]]) else NA_real_; tibble(focus_country=cc,beta_other=b,delta_focus=delta,beta_focus=b+delta,p_delta=pd) }
specs <- tibble(specification=c("baseline","exclude_sri_lanka","exclude_philippines","exclude_both","winsor_1_99","winsor_5_95"), omitted=list(character(),"Sri Lanka","Philippines",focus_countries,character(),character()), winsor=list(NULL,NULL,NULL,NULL,c(.01,.99),c(.05,.95)))
res <- list(); slopes <- list()
for(i in seq_len(nrow(targets))) { h <- targets$hypothesis_id[i]; b <- targets$block[i]; y <- targets$outcome[i]; g <- targets$gpr_measure[i]; x <- make_sample(if(b=="financial")fin else legal,b,y,g); a <- pmap_dfr(specs,function(specification,omitted,winsor) fit_main(x$data,y,g,x$controls,omitted,winsor) %>% mutate(hypothesis_id=h,outcome=y,gpr_measure=g,specification=specification,omitted_countries=paste(omitted,collapse=";"),winsorized_outcome=!is.null(winsor),.before=1)); base <- a %>% filter(specification=="baseline") %>% pull(beta); res[[h]] <- a %>% mutate(sign_matches_baseline=sign(beta)==sign(base),beta_change_from_baseline=beta-base); slopes[[h]] <- map_dfr(focus_countries,~fit_slope(x$data,y,g,x$controls,.x) %>% mutate(hypothesis_id=h,outcome=y,gpr_measure=g,.before=1)) }
robustness <- bind_rows(res); decomposition <- bind_rows(slopes)
summary <- robustness %>% group_by(hypothesis_id,outcome,gpr_measure) %>% summarise(baseline_beta=beta[specification=="baseline"][1],all_sensitivity_signs_match=all(sign_matches_baseline[specification!="baseline"] %in% TRUE),min_p=min(p,na.rm=TRUE),max_abs_beta_change=max(abs(beta_change_from_baseline),na.rm=TRUE),interpretation=if_else(all_sensitivity_signs_match,"Direction survives this transparent sensitivity set","Direction changes in at least one transparency check"),.groups="drop")
write_csv(robustness,file.path(out_dir,"01_robustness_matrix.csv")); write_csv(decomposition,file.path(out_dir,"02_country_slope_decomposition.csv")); write_csv(summary,file.path(out_dir,"03_stage3j_summary.csv"))
md <- c("# Stage 3J Influence Robustness","","This is a transparency diagnostic after Stage 3I; it does not select a preferred sample or delete countries from the baseline.","Country-specific slope decompositions are descriptive, not causal subgroup effects.","","## Results",paste0("- ",summary$hypothesis_id,": ",summary$interpretation,"; baseline beta=",signif(summary$baseline_beta,4),", maximum |beta change|=",signif(summary$max_abs_beta_change,4)))
writeLines(md,file.path(out_dir,"STAGE3J_SUMMARY.md")); cat(paste(md,collapse="\n"),"\n")
